### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by Happybooty** [ShadowOxygen/OxygenX#10]
What python version did you use to make it because when i try to compile the source code on 3.8.2 and 2.7 but it doesn't work.

**Comment by ShadowOxygen** [comment]
Its python 3.7

**Comment by ShadowOxygen** [comment]
Also remember to install the imports (if you don't have it)

**Comment by Happybooty** [comment]
Ok thanks so much!

**Comment by ShadowOxygen** [comment]
No problem.
