### ISSUE TITLE
Issue it doesnt start

### ISSUE THREAD

**Issue by Mika442** [ShadowOxygen/OxygenX#16]
When I start OxygenX it doesnt start at all doesnt matter the proxy, 
proxy type,
.py version or .exe
it doesnt matter they all dont work any help?

**Comment by Mika442** [comment]
Nvm it works now what is the max amount of threads?

**Comment by Happybooty** [comment]
200 is a nice number but I go for around 50 on OxygenX 0.2B but idk what would be good for 0.3. Try stuff out with the same proxy and combo and see which one is best speed and gets you most hits :)

**Comment by Mika442** [comment]
ok thank you noe I have 1 more issue because when I use proxyland.io proxies
it goes like this: start 2k cpm then drop to 500
go up to 700, the all the way down to 0 and get up to 500 again.
and then go to 0 again and that continus

**Comment by Happybooty** [comment]
When it says its at those cpm's does it actually reflect the speed of checking?

**Comment by Mika442** [comment]
yes it gives an realtime representation of the speed.

**Comment by Happybooty** [comment]
What type of proxies are they (Http(s), Socks4/5).

**Comment by Mika442** [comment]
they are http/s

**Comment by Happybooty** [comment]
Welp only thing I can recommend is switching proxy provider. I use oxygenx 0.2B cause I think it has a better cpm and hits more but idk. Try with different proxy providers.

**Comment by Mika442** [comment]
ok I will because it didnt happen before it just started happening since I updated it

**Comment by Happybooty** [comment]
If it still doesn't work then use OxygenX-0.2B as I have not had that issue before :)

**Comment by ghost** [comment]
Happybooty where do you get your proxy's

**Comment by Mika442** [comment]
Yeetmachien I personally have been using proxyland.io for a long time and had 0 issues until now 
but Zenum.io is a good site for proxies to

**Comment by Mika442** [comment]
Hm even with oxygenX-0.2b it just stops around a ranodm part...
weird

**Comment by Happybooty** [comment]
Then I don't know the issue sry :/

**Comment by Happybooty** [comment]
Yeetmachien I get mine from proxy scrape but they are trash.

**Comment by ShadowOxygen** [comment]
@Mika442 The Issue with the proxy dropping and going backup again is a issue that I am aware but I do not know the fix yet

Will try to find out the problem

**Comment by Moezs** [comment]
Hello i have same problem im new to python but i did pip install requests and colorama but still i downloaded source code and put the exe in the folder but neither of the exe or .py works ( i put proxies) can you help me please 
![image](https://user-images.githubusercontent.com/66956309/84664159-695fff00-af1e-11ea-80b3-3b75ae9df900.png)

**Comment by Happybooty** [comment]
Moezs msg me Possessed_Cereal#9357 Maybe I can help :)

**Comment by ShadowOxygen** [comment]
The .py probably doesnt work since you need to install PySocks
