### ISSUE TITLE
Luminati Proxies

### ISSUE THREAD

**Issue by Teals53** [ShadowOxygen/OxygenX#17]
I put luminati proxy into proxy.txt but oxygen not checking accounts with luminati proxy its doesnt start why ?

its work with normal proxies but not work with luminati but u say in main page we support this auth type proxies ?

**Comment by ShadowOxygen** [comment]
So luminati proxies are banned from mojang (They disallowed their proxies from going to mojang's api)

**Comment by Teals53** [comment]
sad
