### ISSUE TITLE
Some bugs(I think)

### ISSUE THREAD

**Issue by QuellaMC** [ShadowOxygen/OxygenX#2]
SOME times the counter left will become negative
and I dont know why it can't have Secured.txt and Unsecured.txt and CapturedData.txt

**Comment by ShadowOxygen** [comment]
Please give me a screenshot

**Comment by QuellaMC** [comment]
![QQ截图20200222124455](https://user-images.githubusercontent.com/35688096/75086654-a8ce9e00-5571-11ea-8989-1291c50522d7.png)

**Comment by QuellaMC** [comment]
It just have these files,doesn't have secure and unsecure and capture files
![QQ截图20200222124556](https://user-images.githubusercontent.com/35688096/75086702-24304f80-5572-11ea-8e48-e6c34c87ca1b.png)

**Comment by ShadowOxygen** [comment]
What is your config?

**Comment by QuellaMC** [comment]
Initial config

**Comment by ShadowOxygen** [comment]
Hmmm not sure what the problem is at the moment
