### ISSUE TITLE
Accounts for a specific server in a .txt

### ISSUE THREAD

**Issue by Tcm9** [ShadowOxygen/OxygenX#23]
Please add a setting in the configs that accounts that work on certain servers should be stored in an extra .txt file.
e.g.
abc@def.com:gehij <- Hive/Gomme alt
klm@op.com:qrst <- Gomme alt

Gomme.txt:
abc@def.com:gehij
klm@op.com:qrst

Hive.txt:
abc@def.com:gehij

If you want to play on a specific server now, e.g. Hive, You can look into the Hive.txt and just take the accounts from there.
![image](https://user-images.githubusercontent.com/31276706/86247603-feb0f380-bbac-11ea-8e7d-e10c84050054.png)

**Comment by ShadowOxygen** [comment]
ehh I cant cuz I dont have a banned checker
