### ISSUE TITLE
OxygenX exits early when running for too long

### ISSUE THREAD

**Issue by winneratwin** [ShadowOxygen/OxygenX#25]
left oxygenx running for 2 days and come back to it not running and it having ~400k accounts left to check and saying it's done [image](https://i.imgur.com/DKhkeQh.png)

**Comment by ShadowOxygen** [comment]
Does your combolist have any errors?

**Comment by winneratwin** [comment]
was a problem with my combo list had a line that was not email:pass 

`bigdaddyTmoney:1959-01-12:thomas.hall@att.net:danielle10`

from now on I'm going to remove lines matching this regex `^.*?:.*?:.+`
