### ISSUE TITLE
Feature request 2

### ISSUE THREAD

**Issue by layou233** [ShadowOxygen/OxygenX#30]
https://github.com/ShadowOxygen/OxygenX/blob/master/OxygenX-0.5.py#L328

The Mojang blocked proxies are unuseful, and it will waste my time to retry alts when queue going to their turn again and again.
So I'm imaging a feature to delete these bad proxies lines from queue and proxies original txt file automatically when the checking program found it is bad. (u have already done the function of checking bad proxies at Line328, just add "auto-delete" feature that can be set to on or off in config.yml)
That is not difficult to make come true but it will be VERY VERY useful for leeched proxies and API provided proxies.
Thanks to u to give us so cool free checker!

**Comment by layou233** [comment]
And another advice: BanChecker
Many chinese paid checker already have this feature.
When successful checked an alt, use the accesstoken to join the server url like a client in config through MCProtocol.
So it can check if the alt has been banned in a server.
HAS A VERY HIGH DIFFICULTY TO DONE THIS FEATURE IN PYTHON
Thanks again whether you r interested at my disgusting advice or not XD

**Comment by ShadowOxygen** [comment]
For the ban checker, I do have some plans to make it
And for the bad proxies, it will be added in 0.6

Thanks for the suggestions!
