### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SerendipityR-2022** [ShadowOxygen/OxygenX#36]
Skywar/Skyblock/Bedwars stats check.

I see this feature in some paid checkers,it can output the levels and coins of bedwars,skyblock and skywars if they reach the set vaule.

Your checker is really good.Thank you!

**Comment by SerendipityR-2022** [comment]
Another suggestion

If due to network reasons, such as a connection timeout or blocked proxy,some combos are not checked.
Please do not classify these combos as "Bad", but "Error".

**Comment by ShadowOxygen** [comment]
> Another suggestion
> 
> If due to network reasons, such as a connection timeout or blocked proxy,some combos are not checked.
> Please do not classify these combos as "Bad", but "Error".

I already did

**Comment by ShadowOxygen** [comment]
> Skywar/Skyblock/Bedwars stats check.
> 
> I see this feature in some paid checkers,it can output the levels and coins of bedwars,skyblock and skywars if they reach the set vaule.
> 
> Your checker is really good.Thank you!

Maybe in the future

**Comment by ShadowOxygen** [comment]
SkyWars/BedWars/SkyBlock Stats Added in 0.7
