### ISSUE TITLE
Legacy name check

### ISSUE THREAD

**Issue by Teals53** [ShadowOxygen/OxygenX#37]
SFA password changer, also new password is set in config with a true/false option

they need a legacy check option so we can make our combos more hq without check useless lines

and og names checker with 1/2/3 letter names too

and maybe mail acces checker not working bcs i check some alt and there is 0 mfa alts but i try that manually and i found some mfa accounts like i can reach their mails (same pass) ? xd

**Comment by ShadowOxygen** [comment]
> SFA password changer, also new password is set in config with a true/false option
> 
> they need a legacy check option so we can make our combos more hq without check useless lines
> 
> and og names checker with 1/2/3 letter names too
> 
> and maybe mail acces checker not working bcs i check some alt and there is 0 mfa alts but i try that manually and i found some mfa accounts like i can reach their mails (same pass) ? xd

1. I won't put SFA/UNFA Pass changer because I don't know the method (Mojang patched the old one) and I don't want to
2. I don't understand your second request
3. 1/2/3/special_character name save is already in OxygenX
4. Email Access is working but some domains may not be supported

**Comment by Teals53** [comment]
> > SFA password changer, also new password is set in config with a true/false option
> > they need a legacy check option so we can make our combos more hq without check useless lines
> > and og names checker with 1/2/3 letter names too
> > and maybe mail acces checker not working bcs i check some alt and there is 0 mfa alts but i try that manually and i found some mfa accounts like i can reach their mails (same pass) ? xd
> 
> 1. I won't put SFA/UNFA Pass changer because I don't know the method (Mojang patched the old one) and I don't want to
> 2. I don't understand your second request
> 3. 1/2/3/special_character name save is already in OxygenX
> 4. Email Access is working but some domains may not be supported

Thx for reply

1. Then okey xD

2. I mean if nickname doesnt exit they not need to check this u can look at this option another checkers too also some paid checkers have that

3. Before i think its not bcs i not see configuration about that anyway sorry its my mistake xd

4. I tried on yahoo outlook and gmail so maybe this domains are not work ?

**Comment by ShadowOxygen** [comment]
> > > SFA password changer, also new password is set in config with a true/false option
> > > they need a legacy check option so we can make our combos more hq without check useless lines
> > > and og names checker with 1/2/3 letter names too
> > > and maybe mail acces checker not working bcs i check some alt and there is 0 mfa alts but i try that manually and i found some mfa accounts like i can reach their mails (same pass) ? xd
> > 
> > 
> > 
> > 1. I won't put SFA/UNFA Pass changer because I don't know the method (Mojang patched the old one) and I don't want to
> > 2. I don't understand your second request
> > 3. 1/2/3/special_character name save is already in OxygenX
> > 4. Email Access is working but some domains may not be supported
> 
> Thx for reply
> 
> 1. Then okey xD
> 2. I mean if nickname doesnt exit they not need to check this u can look at this option another checkers too also some paid checkers have that
> 3. Before i think its not bcs i not see configuration about that anyway sorry its my mistake xd
> 4. I tried on yahoo outlook and gmail so maybe this domains are not work ?



> > > SFA password changer, also new password is set in config with a true/false option
> > > they need a legacy check option so we can make our combos more hq without check useless lines
> > > and og names checker with 1/2/3 letter names too
> > > and maybe mail acces checker not working bcs i check some alt and there is 0 mfa alts but i try that manually and i found some mfa accounts like i can reach their mails (same pass) ? xd
> > 
> > 
> > 
> > 1. I won't put SFA/UNFA Pass changer because I don't know the method (Mojang patched the old one) and I don't want to
> > 2. I don't understand your second request
> > 3. 1/2/3/special_character name save is already in OxygenX
> > 4. Email Access is working but some domains may not be supported
> 
> Thx for reply
> 
> 1. Then okey xD
> 2. I mean if nickname doesnt exit they not need to check this u can look at this option another checkers too also some paid checkers have that
> 3. Before i think its not bcs i not see configuration about that anyway sorry its my mistake xd
> 4. I tried on yahoo outlook and gmail so maybe this domains are not work ?

1. I might add the name check (if the username is unmigrated or not) in the future

2. Yahoo, outlook, and gmail is not supported as far as I know (using aj-https.com's api)

**Comment by Teals53** [comment]
Thats sad xd can u tell me which domanins we need to check manually ?

**Comment by ShadowOxygen** [comment]
> Thats sad xd can u tell me which domanins we need to check manually ?

idk lol

**Comment by Teals53** [comment]
XD

**Comment by ShadowOxygen** [comment]
domains like t-online.de, gmx.de, alice.it, bex.net, etc are supported

**Comment by ShadowOxygen** [comment]
I made legacy name check in 0.8, will close
