### ISSUE TITLE
In OxyganX-0.7.py, he cannot work normally,

### ISSUE THREAD

**Issue by qaz6750** [ShadowOxygen/OxygenX#38]
In OxyganX-0.7.py, it can’t work, and 0.6 is the same, but strangely, it can work normally below 0.5

It prompts such information
File "OxygenX-0.7.py", line 161, in __init__
  File "OxygenX-0.7.py", line 849, in start_checker
AttributeError: 'Main' object has no attribute 'announcement'
[8096] Failed to execute script OxygenX-0.7

I used translator to translate from Chinese to English, it may be a bit inaccurate

**Comment by ShadowOxygen** [comment]
That is a error I'm aware of and will be fixed in 0.8

**Comment by GuoHYZ** [comment]
delete line 849

**Comment by ShadowOxygen** [comment]
......thats not how it works
