### ISSUE TITLE
OxygenX 0.7 problems

### ISSUE THREAD

**Issue by ghost** [ShadowOxygen/OxygenX#41]
Some problems i am having:
Proxy API: true not doing anything
Importing proxies appears to put me in an endless loop or smth, can't close import dialogue box.

I am on macos 10.14.6

**Comment by ShadowOxygen** [comment]
Weird, can I have your config settings?

**Comment by ShadowOxygen** [comment]
You need to change it to input instead

**Comment by ShadowOxygen** [comment]
Tell me if you still have issues
