### ISSUE TITLE
Running python file on MacOS gives errors about modules

### ISSUE THREAD

**Issue by sourcelocation** [ShadowOxygen/OxygenX#45]
Hi. When I try to run python file on my Mac (python3 installed, `pip3 install -r requirements.txt` `python3 OxygenX-0.8.py`) It gives me errors about modules not found. 

exerhythm@Matthews-iMac OxygenX-master % python3 /Users/exerhythm/Downloads/OxygenX-master/OxygenX-0.8.py
Traceback (most recent call last):
  File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/utils.py", line 29, in <module>
    import tkinter as tk  # python3
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/utils.py", line 36, in <module>
    import Tkinter as tk  # python2
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/button_box.py", line 15, in <module>
    from . import utils as ut
  File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/utils.py", line 43, in <module>
    raise ImportError("Unable to find tkinter package.")
ImportError: Unable to find tkinter package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/exerhythm/Downloads/OxygenX-master/OxygenX-0.8.py", line 14, in <module>
    from easygui import fileopenbox
  File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/__init__.py", line 34, in <module>
    from .boxes.button_box import buttonbox
  File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/button_box.py", line 18, in <module>
    import global_state
ModuleNotFoundError: No module named 'global_state'

Any fix? Thanks

**Comment by ghost** [comment]
It aint made for mac

**Comment by sourcelocation** [comment]
I installed Windows 10 Virtual Machine. How can I download the .exe file?
Thanks

**Comment by ShadowOxygen** [comment]
> Hi. When I try to run python file on my Mac (python3 installed, `pip3 install -r requirements.txt` `python3 OxygenX-0.8.py`) It gives me errors about modules not found.
> 
> exerhythm@Matthews-iMac OxygenX-master % python3 /Users/exerhythm/Downloads/OxygenX-master/OxygenX-0.8.py
> Traceback (most recent call last):
> File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/utils.py", line 29, in
> import tkinter as tk # python3
> File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/tkinter/**init**.py", line 36, in
> import _tkinter # If this fails your Python may not be configured for Tk
> ModuleNotFoundError: No module named '_tkinter'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/utils.py", line 36, in
> import Tkinter as tk # python2
> ModuleNotFoundError: No module named 'Tkinter'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/button_box.py", line 15, in
> from . import utils as ut
> File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/utils.py", line 43, in
> raise ImportError("Unable to find tkinter package.")
> ImportError: Unable to find tkinter package.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Users/exerhythm/Downloads/OxygenX-master/OxygenX-0.8.py", line 14, in
> from easygui import fileopenbox
> File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/**init**.py", line 34, in
> from .boxes.button_box import buttonbox
> File "/Users/exerhythm/Library/Python/3.7/lib/python/site-packages/easygui/boxes/button_box.py", line 18, in
> import global_state
> ModuleNotFoundError: No module named 'global_state'
> 
> Any fix? Thanks

The problem is the module easygui since its not made for MacOS

The exe is in the release section
https://github.com/ShadowOxygen/OxygenX/releases
