### ISSUE TITLE
threads does not match the number of actual connections

### ISSUE THREAD

**Issue by bilbillm** [ShadowOxygen/OxygenX#46]
i only set up 200 threads but traffic monitoring software shows that has more than 2000 number of connections. why is that?
![only 200 threads ](https://user-images.githubusercontent.com/60431233/91444132-e4db1680-e8a6-11ea-8217-e9642fa26d6d.png)

**Comment by ShadowOxygen** [comment]
Probably the requests that are waiting.
200 threads doesn't mean 200 connections, it may be more.
