### ISSUE TITLE
working unmigrated mode. not normal mode

### ISSUE THREAD

**Issue by VacCatGT** [ShadowOxygen/OxygenX#50]
so yes normal mode just doesnt check anything unmigrated mode does

**Comment by ShadowOxygen** [comment]
Unmigrated mode works differently than normal mode, if normal is not working for you, please check the following.
1. Make sure all your proxies are working.
2. Make sure your settings file are using the right proxy type and correct timeouts.

**Comment by VacCatGT** [comment]
1. it needs to be 100%?
2. it should be

the issue is that its not outputting anything. the title thing also isnt changing. it looks like might be a proxy issue yea

**Comment by VacCatGT** [comment]
turns out almost all of my proxies were dead. ill look if it works now with these only working ones

**Comment by VacCatGT** [comment]
yep. was the issue
