### ISSUE TITLE
Checks the Username if it's OG

### ISSUE THREAD

**Issue by enes-py** [ShadowOxygen/OxygenX#51]
Saw that mode in some Checker. Basically you input some OG Names into a .txt Text Document and the Checker checks if any of these Hits own these Ingame Names. I already have a list of about 5.000 OG Ingame Names. Let me know if you are ever going to implement that. I could also send you the needed Code for this.
Thanks in advance,
Kind Regards
Enes

**Comment by ShadowOxygen** [comment]
That is basically a IGN checker when OxygenX is a account checker, so I probably won't put that in.
I may do a name checker in the future so look out for it.

-ShadowOxygen
