### ISSUE TITLE
Save Legacy Hits

### ISSUE THREAD

**Issue by Teals53** [ShadowOxygen/OxygenX#52]
so we can check this for normal checking

**Comment by ShadowOxygen** [comment]
It does save legacy hits in normal mode

**Comment by Teals53** [comment]
no they not

**Comment by ShadowOxygen** [comment]
Tt will be only a legacy hit IF the combo is user:pass, Email:password won't be able to login

**Comment by Teals53** [comment]
so not like same as twitch
