### ISSUE TITLE
Better mfa checker

### ISSUE THREAD

**Issue by Teals53** [ShadowOxygen/OxygenX#55]
mfa checker skip lot of hits so i mean after i check my hits mails manually i get some hits but mfa checker cant capture that

**Comment by ShadowOxygen** [comment]
The mail checker api I'm using is limited to some domains, so thats probably why

**Comment by Teals53** [comment]
what about yahoo or gmx ?

**Comment by ShadowOxygen** [comment]
gmx works but not yahoo

**Comment by ShadowOxygen** [comment]
the Api isn't the best but I have yet to see a better one

**Comment by Teals53** [comment]
kk
