### ISSUE TITLE
[Dead keys] Hypixel Api keys

### ISSUE THREAD

**Issue by ShadowOxygen** [ShadowOxygen/OxygenX#6]
The Hypixel api keys that I including in the configs are all dead so most of you guys are not getting the Hypixel checks. 
You can get a new one by going to Hypixel and do /api new, which will give you a new key.

Will be fixed in 0.3.

**Comment by SetsunaYukiOvO** [comment]
Uhhhhhhh,I'll provide five hypixel API keys, but some may fail.
491cfe7f-e3e5-48b5-97ff-4b7d3e5fbe7f
13eaf0d3-381c-428f-9fbd-ea63f2180f42
5549cdea-1378-4b00-b6a4-244b42846bde
3217da80-0202-41a5-8399-df998a4425dd
77de8865-1265-4496-9d79-f8cff96c4c86

**Comment by ShadowOxygen** [comment]
4 of keys are working so I will put it in the config file, Thanks you for providing the keys!

**Comment by ooodlllars** [comment]
ed134a54-b58d-4717-b230-bdd5b3b57de6 take mine lol
