### ISSUE TITLE
i can't run it on linux machine

### ISSUE THREAD

**Issue by yoooby** [ShadowOxygen/OxygenX#9]

**Comment by ShadowOxygen** [comment]
OxygenX isn't meant for Linux, but if you do want to run it, remove all the lines with ctype

**Comment by RedW0lfStoneYT** [comment]
> _No description provided._

Did it work for you? If so can you please send me the files? I tried to do it how ShadowBlader suggested (I do have python knowledge) but it didn't seem to work for me...
